apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.svc.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  type: {{ .Values.application.svc.type }}
  selector:             
    app: {{ .Values.application.selector }}
  ports:
    - port: {{ .Values.application.container.port }}
